# Generated by Django 3.0.8 on 2020-07-17 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_height', models.PositiveIntegerField()),
                ('img_width', models.PositiveIntegerField()),
                ('img', models.ImageField(height_field='img_height', upload_to='sias', width_field='img_width')),
                ('wstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia_app.WorkStream')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia_app.WorkStream')),
            ],
        ),
        migrations.CreateModel(
            name='ABox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=5, max_digits=20)),
                ('y', models.DecimalField(decimal_places=5, max_digits=20)),
                ('w', models.DecimalField(decimal_places=5, max_digits=20)),
                ('h', models.DecimalField(decimal_places=5, max_digits=20)),
                ('sia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia_app.SIA')),
            ],
        ),
    ]
