# Generated by Django 3.0.8 on 2020-07-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sia_app', '0002_auto_20200717_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abox',
            old_name='x',
            new_name='orig_x',
        ),
        migrations.RenameField(
            model_name='abox',
            old_name='y',
            new_name='orig_y',
        ),
    ]
