# Generated by Django 3.0.8 on 2020-07-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia_app', '0003_auto_20200717_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abox',
            name='h',
            field=models.DecimalField(decimal_places=15, max_digits=25),
        ),
        migrations.AlterField(
            model_name='abox',
            name='orig_x',
            field=models.DecimalField(decimal_places=15, max_digits=25),
        ),
        migrations.AlterField(
            model_name='abox',
            name='orig_y',
            field=models.DecimalField(decimal_places=15, max_digits=25),
        ),
        migrations.AlterField(
            model_name='abox',
            name='w',
            field=models.DecimalField(decimal_places=15, max_digits=25),
        ),
    ]
